package com.example.test6.food.test

data class TotalNutrients(
    val CA: CA,
    val CHOCDF: CHOCDFXX,
    val CHOLE: CHOLEXX,
    val ENERC_KCAL: ENERCKCALXX,
    val FAMS: FAMSX,
    val FAPU: FAPUX,
    val FASAT: FASATXX,
    val FAT: FATXX,
    val FE: FEXX,
    val FIBTG: FIBTGXX,
    val FOLAC: FOLACX,
    val FOLDFE: FOLDFEXX,
    val FOLFD: FOLFDX,
    val K: KXX,
    val MG: MGXX,
    val NA: NAXX,
    val NIA: NIAXX,
    val P: PXX,
    val PROCNT: PROCNTXX,
    val RIBF: RIBFXX,
    val SUGAR: SUGARX,
    val THIA: THIAXX,
    val TOCPHA: TOCPHAXX,
    val VITA_RAE: VITARAEXX,
    val VITB12: VITB12XX,
    val VITB6A: VITB6AXX,
    val VITC: VITCXX,
    val VITD: VITDXX,
    val VITK1: VITK1XX,
    val WATER: WATERX,
    val ZN: ZNXX
)